export const NEW_ORDER_REQUEST = "NEW_ORDER_REQUEST"
export const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS"
export const NEW_ORDER_FAIL = "NEW_ORDER_FAIL"

export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST"
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS"
export const MY_ORDER_FAIL = "MY_ORDER_FAIL"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"